import React from 'react'
import logo1 from "../images/logo1.png"

const MusicRadio= () => {
  return (
    <div>
        
    
        
            
                <div class="lw">
                    <h1><a href="https://www.nairaland.com/" class="g" title="Nairaland, the Nigerian Forum"><img src={logo1} width={246} height={24}/></a></h1> Welcome, <b>Guest</b>: <b><a href="/register">Register On Nairaland</a></b> / <a href="/login">LOGIN!</a>                    / <a href="/trending">Trending</a> / <a href="/recent">Recent</a> / <a href="/topics">New</a><br/><b>Stats: </b>2,952,742 members, 7,157,059 topics. <b>Date</b>: Monday, 07 November 2022 at 01:31 PM
                    <p>
                        <form action="/search"> <input type="text" name="q" size="32"/>
                            <input type="submit" name="search" value="Search"/></form>
                            </p>
                            </div>

                            <h4>Music/Radio - Nairaland</h4>
        <p class=""><a href="/">Nairaland Forum</a> / <a href="/entertainment">Entertainment</a> / <a href="/musicradio">Music/Radio</a>
            </p>

            <div className='tr'><b><a href="/rap-battles">Rap Battles</a></b>: Battle rhymes, rap warfare, hip-hop contests. You know what I mean! (2382 topics)</div>
                            <tr/>
                                <div class="r"><b><a href="/music">Music Business</a></b>: Music production, advertisements, et cetera. (6615 topics)</div>
                <p><a href="/musicradio">Music/Radio</a>: Talk about your favorite songs, music albums, artists and bands. <b>Ad Rate</b>: <a href="/adrates">₦<b>2,346.34</b>/week (<b>63.9</b>% discount)</a>.<br/>
                    <div class="vertipics"><a href="/musicradio" rel="sponsored"><img src="https://www.nairaland.com/vertipics/yuy9vjlludrigbaeowz0get7rtvxcqm6.png" alt=''/></a><a href="/musicradio" rel="sponsored"><img src="https://www.nairaland.com/vertipics/ujsti16vmkvlxuxyzafqz3hlbs1j0np6.png" alt=''/></a>
                        <a
                            href="/musicradio" rel="sponsored"><img src="https://www.nairaland.com/vertipics/ujsti16vmkvlxuxyzafqz3hlbs1j0np6.png" alt=''/></a>
                    </div>
                    
                    </p>

                    <p> <b>(1)</b> <a href="https://www.nairaland.com/music-radio/1">(2)</a> <a href="https://www.nairaland.com/music-radio/2">(3)</a> <a href="https://www.nairaland.com/music-radio/3">(4)</a> <a href="https://www.nairaland.com/music-radio/4">(5)</a>                        <a href="https://www.nairaland.com/music-radio/5">(6)</a> <a href="https://www.nairaland.com/music-radio/6">(7)</a> <a href="https://www.nairaland.com/music-radio/7">(8)</a> <a href="https://www.nairaland.com/music-radio/8">(9)</a>                        <a href="https://www.nairaland.com/music-radio/9">(10)</a> (of <b>2455</b> pages) (<a href="https://www.nairaland.com/newtopic?board=3">Create New Topic</a>) (<a class="unft" onClick="handlefollows('https://www.nairaland.com/do_unfollowboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fmusic-radio&amp;board=3', 'https://www.nairaland.com/do_followboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fmusic-radio&amp;board=3', '0', 'Follow', 'Un-Follow', 'unft'); return false;"
                            href="https://www.nairaland.com/do_followboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fmusic-radio&amp;board=3">Follow</a>) (<a href="https://www.nairaland.com/mailmods?board=3">Mail Mods</a>)
                        </p>


                            <div className='tr'>Topic: <a href="/music-radio/posts">Posts</a> / <a href="/music-radio/views">Views</a> / <b>Updated</b> / <a href="/music-radio/new">New</a></div>
                                        <tr/>
                                            <div  class="r"><a name="813741"></a>  <b><a href="/813741/what-music-listening-right-now">What Music Are You Listening To Right Now?</a> </b> <a href="https://www.nairaland.com/813741/what-music-listening-right-now/1">(2)</a>                                                <a href="https://www.nairaland.com/813741/what-music-listening-right-now/2">(3)</a> <a href="https://www.nairaland.com/813741/what-music-listening-right-now/3">(4)</a> ... <a href="https://www.nairaland.com/813741/what-music-listening-right-now/1186">(1187)</a>                                                <a href="https://www.nairaland.com/813741/what-music-listening-right-now/1187">(1188)</a> <a href="https://www.nairaland.com/813741/what-music-listening-right-now/1188">(1189)</a>                                                <b>*</b> <br/><span class="s">by <b><a href="/mobf">mobf</a></b>. <b>38030</b> posts &amp; <b>1066771</b> views. <b>11:08am</b> (<b><a href="/viking07">Viking07</a></b>)</span>
                                                <tr/>
                                                </div>
                                                    <div  class="tr"><a name="6974573"></a>  <b><a href="/6974573/2022-nigerian-idol-season-7">2022 Nigerian Idol Season 7 (Official Thread)</a> </b> <a href="https://www.nairaland.com/6974573/2022-nigerian-idol-season-7/1">(2)</a>                                                        <a href="https://www.nairaland.com/6974573/2022-nigerian-idol-season-7/2">(3)</a> <a href="https://www.nairaland.com/6974573/2022-nigerian-idol-season-7/3">(4)</a> ... <a href="https://www.nairaland.com/6974573/2022-nigerian-idol-season-7/11">(12)</a>                                                        <a href="https://www.nairaland.com/6974573/2022-nigerian-idol-season-7/12">(13)</a> <a href="https://www.nairaland.com/6974573/2022-nigerian-idol-season-7/13">(14)</a> <b>*</b> <br/><span class="s">by <b><a href="/sassiemyk">sassiemyk</a></b>. <b>436</b> posts &amp; <b>29627</b> views. <b>1:48pm</b> On <b>Nov 01</b> (<b><a href="/ellajoo">Ellajoo</a></b>)</span>
                                                        <tr/>
                                                        </div>
                                                            <div  class="r"><a name="6410112"></a> <b><a href="/6410112/fela-kuti-nominated-2021-rock">Fela Kuti Nominated For 2021 Rock, Roll Hall Of Fame</a> </b> <a href="https://www.nairaland.com/6410112/fela-kuti-nominated-2021-rock/1">(2)</a>                                                                <a href="https://www.nairaland.com/6410112/fela-kuti-nominated-2021-rock/2">(3)</a> <a href="https://www.nairaland.com/6410112/fela-kuti-nominated-2021-rock/3">(4)</a> <a href="https://www.nairaland.com/6410112/fela-kuti-nominated-2021-rock/4">(5)</a>                                                                <a href="https://www.nairaland.com/6410112/fela-kuti-nominated-2021-rock/5">(6)</a> <b>*</b> <br/><span class="s">by <b><a href="/olatdove">olatdove</a></b>. <b>164</b> posts &amp; <b>48986</b> views. <b>6:16am</b> On <b>Sep 21</b> (<b><a href="/josh556627">Josh556627</a></b>)</span>
                                                                <tr/>
                                                                </div>
                                                                    <div class="tr"><a name="228376"></a>  <b><a href="/228376/welcome-music-section-updated-27-01-2013">Welcome To The Music Section (&quot;_&quot;) . . . .(Updated 27-01-2013)</a> </b><br/>
                                                                        <span
                                                                            class="s">by <b><a href="/lalaboi">lalaboi</a></b>. <b>3</b> posts &amp; <b>133764</b> views. <b>2:52am</b> On <b>Jan 27</b>, <b>2013</b> (<b><a href="/mynd44">Mynd44</a></b>)</span>
                                                                            <tr/>
                                                                            </div>
                                                                                <div  class="r"><a name="7409845"></a>  <b><a href="/7409845/wizkid-drops-another-2022-single">WIZKID Drops Another 2022 Single</a> </b>                                                                                   <br/><span class="s">by <b><a href="/gustoafrica">GustoAfrica</a></b>. <b>3</b> posts &amp; <b>247</b> views. <b>1:31pm</b> (<b><a href="/fadal">fadal</a></b>)</span>
                                                                                    <tr/>
                                                                                    </div>
                                                                                        <div  class="tr"><a name="7015450"></a>  <b><a href="/7015450/vacant-billboards-lekki-lagos">Vacant Billboards In Lekki, Lagos</a> </b>                                                                                             <br/><span class="s">by <b><a href="/nijaposters">NijaPOSTERS</a></b>. <b>9</b> posts &amp; <b>829</b> views. <b>10:28am</b> (<b><a href="/wartbumpkeloid">WartBumpKeloid</a></b>)</span>
                                                                                            <tr/>
                                                                                            </div>
                                                                                                <div class="r"><a name="7415409"></a>  <b><a href="/7415409/blaqbonez-story-before-back-uni">Who Is Blaqbonez? Story Before &quot;Back In Uni&quot; [video]</a> </b>                                                                                                    <br/><span class="s">by <b><a href="/tommy6000">Tommy6000</a></b>. <b>8</b> posts &amp; <b>154</b> views. <b>10:08am</b> (<b><a href="/tommy6000">Tommy6000</a></b>)</span>
                                                                                                    <tr/>
                                                                                                    </div>
                                                                                                        <div class="tr"><a name="7420819"></a>  <b><a href="/7420819/there-several-ways-increase-size">There Are Several Ways To Increase The Size Of Your Profile Picture On Instagram</a> </b>                                                                                                            <br/><span class="s">by <b><a href="/verixe">Verixe</a></b>. <b>1</b> post &amp; <b>27</b> views. <b>8:53am</b> (<b><a href="/verixe">Verixe</a></b>)</span>
                                                                                                            <tr/>
                                                                                                            </div>
                                                                                                                <div class="r"><a name="7420750"></a>  <b><a href="/7420750/house-boy-sang-burna-boys">This House Boy Sang Burna Boy&#x27;s Common Person With Passion!</a> </b>                                                                                                               <br/><span class="s">by <b><a href="/jitesmallz">jitesmallz</a></b>. <b>1</b> post &amp; <b>41</b> views. <b>7:58am</b> (<b><a href="/jitesmallz">jitesmallz</a></b>)</span>
                                                                                                                    <tr/>
                                                                                                                    </div>
                                                                                                                        < div class="tr"><a name="7420562"></a>  <b><a href="/7420562/best-hip-hop-music-download">Best Hip Hop Music Download Platform</a> </b>                                                                                                                  <br/><span class="s">by <b><a href="/thejoyof6">Thejoyof6</a></b>. <b>2</b> posts &amp; <b>37</b> views. <b>7:52am</b> (<b><a href="/lonthomas">Lonthomas</a></b>)</span>
                                                                                                                            <tr/>
                                                                                                                            </div>
                                                                                                                                <div class="r"><a name="7420675"></a>  <b><a href="/7420675/ceegospel-network">Ceegospel Network</a> </b>                                                                                                                                     <br/><span class="s">by <b><a href="/ceegospelblog">Ceegospelblog</a></b>. <b>1</b> post &amp; <b>32</b> views. <b>7:07am</b> (<b><a href="/ceegospelblog">Ceegospelblog</a></b>)</span>
                                                                                                                                    <tr/>
                                                                                                                                    </div>
                                                                                                                                        <div  class="tr"><a name="7413121"></a>  <b><a href="/7413121/nigerians-irregular-tastes-music">Nigerians And Their Irregular Tastes For Music.</a> </b>                                                                                                                                            <a href="https://www.nairaland.com/7413121/nigerians-irregular-tastes-music/1">(2)</a> <a href="https://www.nairaland.com/7413121/nigerians-irregular-tastes-music/2">(3)</a>                                                                                                                                            <a href="https://www.nairaland.com/7413121/nigerians-irregular-tastes-music/3">(4)</a>                                                                                                                                           <b>*</b> <br/><span class="s">by <b><a href="/ungodly">Ungodly</a></b>. <b>127</b> posts &amp; <b>18657</b> views. <b>4:43am</b> (<b><a href="/samuelthaking">samuelthaking</a></b>)</span>
                                                                                                                                            <tr/>
                                                                                                                                            </div>
                                                                                                                                                <div class="r"><a name="7415427"></a>  <b><a href="/7415427/burna-boy-really-made-100m">Has Burna Boy Really Made $100M In Year 2022?</a> </b>                                                                                                                                                    <br/><span class="s">by <b><a href="/gustoafrica">GustoAfrica</a></b>. <b>2</b> posts &amp; <b>175</b> views. <b>9:04pm</b> On <b>Nov 06</b> (<b><a href="/fadal">fadal</a></b>)</span>
                                                                                                                                                    <tr/>
                                                                                                                                                    </div>
                                                                                                                                                        <div  class="tr"><a name="7420154"></a>  <b><a href="/7420154/kizz-daniel-cokoboi-music">Kizz Daniel Cokoboi [music]</a> </b>                                                                                                                                                             <br/><span class="s">by <b><a href="/cokooboi">Cokooboi</a></b>. <b>1</b> post &amp; <b>50</b> views. <b>7:12pm</b> On <b>Nov 06</b> (<b><a href="/cokooboi">Cokooboi</a></b>)</span>
                                                                                                                                                            <tr/>
                                                                                                                                                            </div>
                                                                                                                                                                <div  class="r"><a name="7420152"></a>  <b><a href="/7420152/how-get-sponsors-music-one">How To Get Sponsors For Your Music In One Month Or Less</a> </b>                                                                                                                                                                    <br/><span class="s">by <b><a href="/bilkisuabdul">BilkisuAbdul</a></b>. <b>1</b> post &amp; <b>38</b> views. <b>7:10pm</b> On <b>Nov 06</b> (<b><a href="/bilkisuabdul">BilkisuAbdul</a></b>)</span>
                                                                                                                                                                    <tr/>
                                                                                                                                                                    </div>
                                                                                                                                                                        <div  class="tr"><a name="7420133"></a>  <b><a href="/7420133/get-resell-phone-dstv-app">Get And Resell This Phone Dstv App.</a> </b>                                                                                                                                                                           <br/><span class="s">by <b><a href="/moneybloke">Moneybloke</a></b>. <b>1</b> post &amp; <b>43</b> views. <b>6:55pm</b> On <b>Nov 06</b> (<b><a href="/moneybloke">Moneybloke</a></b>)</span>
                                                                                                                                                                            <tr/>
                                                                                                                                                                            </div>
                                                                                                                                                                                <div class="r"><a name="7419751"></a>  <b><a href="/7419751/leaked-kizz-daniel-ft-naira">Leaked: Kizz Daniel Ft Naira Marley - Odo _naijahitplay</a> </b>                                                                                                                                                                                     <br/><span class="s">by <b><a href="/9jahitplay">9jahitplay</a></b>. <b>1</b> post &amp; <b>69</b> views. <b>1:56pm</b> On <b>Nov 06</b> (<b><a href="/9jahitplay">9jahitplay</a></b>)</span>
                                                                                                                                                                                    <tr/>
                                                                                                                                                                                    </div>
                                                                                                                                                                                        <div class="tr"><a name="6401339"></a>  <b><a href="/6401339/how-setup-launch-internet-radio">How To Setup And Launch Your Internet Radio Easily</a> </b><br/>
                                                                                                                                                                                            <span
                                                                                                                                                                                                class="s">by <b><a href="/bigajeff">Bigajeff</a></b>. <b>4</b> posts &amp;
                                                                                                                                                                                                <b>341</b> views. <b>12:48pm</b> On <b>Nov 06</b> (<b><a href="/samken2">Samken2</a></b>)</span>
                                                                                                                                                                                                <tr/>
                                                                                                                                                                                                </div>
                                                                                                                                                                                                    <div class="r"><a name="7419336"></a>                                                                                                                                                                                                        <b><a href="/7419336/gospel-music-eyekingdazzle-god-blessed">Gospel Music: Eyekingdazzle – Our God Has Blessed Me Ft. Cobhams Asuquo</a> </b><br/>
                                                                                                                                                                                                        <span
                                                                                                                                                                                                            class="s">by <b><a href="/obawonder">obawonder</a></b>. <b>1</b>                                                                                                                                                                                                            post &amp; <b>63</b> views. <b>8:13am</b> On <b>Nov 06</b>                                                                                                                                                                                                            (<b><a href="/obawonder">obawonder</a></b>)</span>
                                                                                                                                                                                                            <tr/>
                                                                                                                                                                                                            </div>




                                 <p> <b>(1)</b> <a href="https://www.nairaland.com/music-radio/1">(2)</a> <a href="https://www.nairaland.com/music-radio/2">(3)</a> <a href="https://www.nairaland.com/music-radio/3">(4)</a> <a href="https://www.nairaland.com/music-radio/4">(5)</a>                                <a href="https://www.nairaland.com/music-radio/5">(6)</a> <a href="https://www.nairaland.com/music-radio/6">(7)</a> <a href="https://www.nairaland.com/music-radio/7">(8)</a> <a href="https://www.nairaland.com/music-radio/8">(9)</a>                                <a href="https://www.nairaland.com/music-radio/9">(10)</a> (of <b>2455</b> pages) (<a href="https://www.nairaland.com/newtopic?board=3">Create New Topic</a>) (<a class="unft" onClick="handlefollows('https://www.nairaland.com/do_unfollowboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fmusic-radio&amp;board=3', 'https://www.nairaland.com/do_followboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fmusic-radio&amp;board=3', '0', 'Follow', 'Un-Follow', 'unft'); return false;"
                                    href="https://www.nairaland.com/do_followboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fmusic-radio&amp;board=3">Follow</a>) (<a href="https://www.nairaland.com/mailmods?board=3">Mail Mods</a>)
                                    </p>
                                <p> (Moderators: <a href="https://www.nairaland.com/airmark">airmark</a>)
                                </p>
                                    <div class="vertipics"><a href="/hopto/music-radio/16436" rel="sponsored"><img src="https://www.nairaland.com/vertipics/tk6suy8on4a62l95jytu0y98018wo5tn.jpg" alt=''/></a><a href="/hopto/music-radio/111" rel="sponsored"><img src="https://www.nairaland.com/vertipics/ujsti16vmkvlxuxyzafqz3hlbs1j0np6.png" alt=''/></a>
                                        <a
                                            href="/hopto/music-radio/16427" rel="sponsored"><img src="https://www.nairaland.com/vertipics/vs5eawfxtjx9roh2pw7v43vm09pe5twt.jpg" alt=''/></a>
                                    </div>
                                    <p class="nocopy">Viewing this board: <a href="/winneygirl">Winneygirl</a>(<span class="f">f</span>), <a href="/chyna01">Chyna01</a>(<span class="m">m</span>), <a href="/neyocool">neyocool</a>(<span class="m">m</span>), <a href="/dontkill">DontKill</a>,
                                        <a href="/vinesrealty">VinesRealty</a>, <a href="/femsyn">Femsyn</a>(<span class="m">m</span>), <a href="/racheal12">Racheal12</a> and 30 guest(s)
                                        </p>
                                        <p class="small">(<a href="#up"><b>Go Up</b></a>)
                                            </p>




                                            <div class="lw">
                                                        <p>
                                                            <form action="/search"> <input type="text" name="q" size="32"/>
                                                                <input type="submit" name="search" value="Search"/></form>Sections: <a href="/politics">politics</a> <a href="/politics/1">(1)</a> <a href="/business">business</a> <a href="/autos">autos</a>                                                            <a href="/autos/1">(1)</a> <a href="/jobs">jobs</a> <a href="/jobs/1">(1)</a> <a href="/career">career</a> <a href="/education">education</a> <a href="/education/1">(1)</a> <a href="/romance">romance</a>                                                            <a href="/computers">computers</a> <a href="/phones">phones</a> <a href="/travel">travel</a> <a href="/sports">sports</a> <a href="/fashion">fashion</a> <a href="/health">health</a> <br/> <a href="/religion">religion</a>                                                            <a href="/celebs">celebs</a> <a href="/tv-movies">tv-movies</a> <a href="/music-radio">music-radio</a> <a href="/literature">literature</a> <a href="/webmasters">webmasters</a> <a href="/programming">programming</a>                                                            <a href="/technologymarket">techmarket</a>
                                                            <p>Links: <a href="/news" title="Page 1, Nairaland News ">(1)</a> <a href="/news/1" title="Page 2, Nairaland News ">(2)</a> <a href="/news/2" title="Page 3, Nairaland News ">(3)</a> <a href="/news/3"
                                                                    title="Page 4, Nairaland News ">(4)</a> <a href="/news/4" title="Page 5, Nairaland News ">(5)</a> <a href="/news/5" title="Page 6, Nairaland News ">(6)</a> <a href="/news/6" title="Page 7, Nairaland News ">(7)</a>                                                                <a href="/news/7" title="Page 8, Nairaland News ">(8)</a> <a href="/news/8" title="Page 9, Nairaland News ">(9)</a> <a href="/news/9" title="Page 10, Nairaland News ">(10)</a>
                                                                <p><b><a href="/" title="Nigerian Forum">Nairaland</a></b> - Copyright &copy; 2005 - 2022 <a href="http://www.seunosewa.com" title="Seun">Oluwaseun Osewa</a>. All rights reserved. See <a href="https://www.nairaland.com/1049481/how-place-targeted-ads-nairaland">How To Advertise</a>.
                                                                    113<br/><b>Disclaimer</b>: Every Nairaland member is <b>solely responsible</b> for <b>anything</b> that he/she <b>posts</b> or <b>uploads</b> on Nairaland.
                                                         </p>
                                                         </p>
                                                         </p>
                                                         </div>
                                               
                                         </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                              
          
                            
    
    
    
  )
}

export default MusicRadio