import React from 'react'
import logo1 from "../images/logo1.png"
import "./home.css"

const NairalandAds = () => {
  return (
    <div>
       
       <table summary="" id="up">
            <tr/>
                <div class="lw">
                    <h1><a href="https://www.nairaland.com/" class="g" title="Nairaland, the Nigerian Forum"><img src={logo1} width={246} height={24} alt=''/></a></h1>Welcome, <a href="/racheal12" class="user">Racheal12</a>: <a href="/editprofile">Edit Profile</a>                    / <a href="/shared"><span title="Posts Shared With Me">SH</span></a> / <a href="/followed"><span title="Followed Topics">FT</span></a> / <a href="/followedboards"><span title="Followed Boards">FB</span></a> / <a href="/likesandshares"><span title="My Likes &amp; Shares">L&amp;S</span></a>                    / <a href="/mentions"><span title="Mentions">MT</span></a> / <a href="/following"><span title="Following">FG</span></a> / <a href="/followers"><span title="Followers">FS</span></a> / <a href="/trending">Trending</a> / <a href="/recent">Recent</a>                    / <a href="/topics">New</a> <br/><b>Stats: </b>2,958,092 members, 7,173,314 topics. <b>Date</b>: Thursday, 17 November 2022 at 10:57 AM / <a href="https://www.nairaland.com/do_logout?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;m=3032616">Logout</a>(
                    <a
                        href="https://www.nairaland.com/do_logout?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;m=3032616&amp;logoutall=1">all</a>)
                        <p>
                            <form action="/search"> <input type="text" name="q" size="32"/>
                                <input type="submit" name="search" value="Search"/></form>
                                </p>
                                </div>
        
        <h4>Nairaland Ads - Nairaland</h4>
        <p class="bold"><a href="/">Nairaland Forum</a> / <a href="/nairalandgeneral">Nairaland / General</a> / <a href="/nairalandads">Nairaland Ads</a>
        </p>
            <p><a href="/ads">Nairaland Ads</a>: Nairaland Direct Adverts <b>Ad Rate</b>: <a href="/adrates">₦<b>422.97</b>/week (<b>67.3</b>% premium)</a>.<br>
            </br>
                <div class="vertipics"><a href="/nairalandads" rel="sponsored"><img src="https://www.nairaland.com/vertipics/y5ihy5vrphmgsghfnk5quunw1pxtsou1.jpg" alt=''/></a><a href="/nairalandads" rel="sponsored"><img src="https://www.nairaland.com/vertipics/r79ybgn96jez0m7ftrrpnhj4efz8dfl3.png" alt=''/></a>
                    <a
                        href="/nairalandads" rel="sponsored"><img src="https://www.nairaland.com/vertipics/o6yj83zlv000iuj2cypyjpaz97owtkw3.png" alt=''/></a>
                </div>
                <p> <b>(1)</b> (of <b>1</b> pages) (<a href="https://www.nairaland.com/newtopic?board=80">Create New Topic</a>) (<a class="unft" onClick="handlefollows('https://www.nairaland.com/do_unfollowboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fads&amp;board=80', 'https://www.nairaland.com/do_followboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fads&amp;board=80', '0', 'Follow', 'Un-Follow', 'unft'); return false;"
                        href="https://www.nairaland.com/do_followboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fads&amp;board=80">Follow</a>) (<a href="https://www.nairaland.com/mailmods?board=80">Mail Mods</a>)
                    </p>
                    </p>
                    </table>
                    <tr/>
                                <div className='tr'>Topic: <a href="/nairalandads">Posts</a> / <a href="/nairalandads">Views</a> / <b>Updated</b> / <a href="/nairalandads">New</a>
                                    <tr/>
                                    </div>
                                        <div  className="r"><a name="4708901"></a> <img src="/icons/normal_post.gif" alt=''/> <b><a href="/4708901/grab-best-practices-live-chat">Grab The Best Practices From Our Live Chat Experts</a> </b> <a href="https://www.nairaland.com/4708901/grab-best-practices-live-chat/1">(2)</a>                                            <a href="https://www.nairaland.com/4708901/grab-best-practices-live-chat/2">(3)</a> <a href="https://www.nairaland.com/4708901/grab-best-practices-live-chat/3">(4)</a> <a href="https://www.nairaland.com/4708901/grab-best-practices-live-chat/4">(5)</a>                                            <br/><span class="s">by <b><a href="/livechatprovide">Livechatprovide</a></b>. <b>145</b> posts &amp; <b>16553</b> views. <b>3:56pm</b> On <b>Nov 03</b> (<b><a href="/shola7499">SHOLA7499</a></b>)</span>
                                            <tr/>
                                            </div>
                                                <div className="tr"><a name="1494985"></a> <img src="/icons/normal_post.gif" alt=''/> <b><a href="/1494985/results-dynamic-ad-design-contest">Results Of Dynamic Ad Design Contest</a> </b> <a href="https://www.nairaland.com/1494985/results-dynamic-ad-design-contest/1">(2)</a>                                                    <a href="https://www.nairaland.com/1494985/results-dynamic-ad-design-contest/2">(3)</a> <a href="https://www.nairaland.com/1494985/results-dynamic-ad-design-contest/3">(4)</a> ... <a href="https://www.nairaland.com/1494985/results-dynamic-ad-design-contest/10">(11)</a>                                                    <a href="https://www.nairaland.com/1494985/results-dynamic-ad-design-contest/11">(12)</a> <a href="https://www.nairaland.com/1494985/results-dynamic-ad-design-contest/12">(13)</a> <b>*</b> <br/>
                                                    <span
                                                        class="s">by <b><a href="/seun">Seun</a></b>. <b>405</b> posts &amp; <b>163139</b> views. <b>11:11am</b> On <b>Oct 16</b> (<b><a href="/codedmedia40668">Codedmedia40668</a></b>)</span>
                                                        <tr/>
                                                        </div>
                                                            <div className="r"><a name="6618281"></a> <img src="/icons/normal_post.gif" alt=''/> <b><a href="/6618281/experience-nairaland-paid-ad">My Experience With Nairaland Paid Ad</a> </b> <a href="https://www.nairaland.com/6618281/experience-nairaland-paid-ad/1">(2)</a>                                                                <br/><span class="s">by <b><a href="/solaredge">SolarEdge</a></b>. <b>34</b> posts &amp; <b>11100</b> views. <b>5:25am</b> On <b>Aug 30</b>, <b>2021</b>  (<b><a href="/cordenify">Cordenify</a></b>)</span>
                                                                <tr/>
                                                                </div>
                                                                    <div class="tr"><a name="1490215"></a> <img src="/icons/normal_post.gif" alt=''/> <b><a href="/1490215/first-nairaland-dynamic-ad-design">First Nairaland Dynamic Ad Design Contest</a> </b> <a href="https://www.nairaland.com/1490215/first-nairaland-dynamic-ad-design/1">(2)</a>                                                                        <a href="https://www.nairaland.com/1490215/first-nairaland-dynamic-ad-design/2">(3)</a> <a href="https://www.nairaland.com/1490215/first-nairaland-dynamic-ad-design/3">(4)</a> ...
                                                                        <a href="https://www.nairaland.com/1490215/first-nairaland-dynamic-ad-design/19">(20)</a> <a href="https://www.nairaland.com/1490215/first-nairaland-dynamic-ad-design/20">(21)</a>                                                                        <a href="https://www.nairaland.com/1490215/first-nairaland-dynamic-ad-design/21">(22)</a> <b>*</b> <br/><span class="s">by <b><a href="/seun">Seun</a></b>. <b>694</b> posts &amp; <b>87714</b> views. <b>2:47pm</b> On <b>Dec 25</b>, <b>2017</b>  (<b><a href="/hamxee33">hamxee33</a></b>)</span>

                                                                        <tr/>
                                                                        </div>
                                                                        
                                                                            <div className="r"><a name="3878350"></a> <img src="/icons/normal_post.gif" alt=''/> <b><a href="/3878350/advert-not-active-after-payment">Advert Not Active After Payment</a> </b><br/><span class="s">by <b><a href="/titus1">titus1</a></b>. <b>4</b> posts &amp; <b>16368</b> views. <b>10:35am</b> On <b>Jun 24</b>, <b>2017</b>  (<b><a href="/seun">Seun</a></b>)</span>
                                                                                <tr/>
                                                                                </div>
                                                                                    <div className="tr"><a name="3528862"></a> <img src="/icons/normal_post.gif" alt=''/> <b><a href="/3528862/non-credit-account">Non Credit Of Account</a> </b><br/><span class="s">by <b><a href="/mobileman829">Mobileman829</a></b>. <b>2</b> posts &amp; <b>16221</b> views. <b>9:02am</b> On <b>Dec 20</b>, <b>2016</b>  (<b><a href="/seun">Seun</a></b>)</span>
                                                                                        <tr/>
                                                                                        </div>
                                                                                            <div className="r"><a name="2906831"></a> <img src="/icons/normal_post.gif" alt=''/> <b><a href="/2906831/nairaland-ads-question">Nairaland Ads Question</a> </b><br/><span class="s">by <b><a href="/nalaugh">NaLaugh</a></b>. <b>2</b> posts &amp; <b>19650</b> views. <b>8:22am</b> On <b>Feb 02</b>, <b>2016</b>  (<b><a href="/seun">Seun</a></b>)</span>
                                                                                                <tr/>
                                                                                                </div>
                                                                                                    <div className="tr"><a name="1501201"></a> <img src="/icons/normal_post.gif" alt=''/> <b><a href="/1501201/discussion-nairalands-new-targeted-ads">Discussion Of Nairaland&#x27;s New Targeted Ads</a> </b>                                                                                                        <a href="https://www.nairaland.com/1501201/discussion-nairalands-new-targeted-ads/1">(2)</a> <a href="https://www.nairaland.com/1501201/discussion-nairalands-new-targeted-ads/2">(3)</a>                                                                                                        <a href="https://www.nairaland.com/1501201/discussion-nairalands-new-targeted-ads/3">(4)</a> ... <a href="https://www.nairaland.com/1501201/discussion-nairalands-new-targeted-ads/19">(20)</a>                                                                                                        <a href="https://www.nairaland.com/1501201/discussion-nairalands-new-targeted-ads/20">(21)</a> <a href="https://www.nairaland.com/1501201/discussion-nairalands-new-targeted-ads/21">(22)</a>                                                                                                        <br/><span class="s">by <b><a href="/seun">Seun</a></b>. <b>703</b> posts &amp; <b>87410</b> views. <b>5:40pm</b> On <b>Feb 11</b>, <b>2015</b>  (<b><a href="/rexwoods">Rexwoods</a></b>)</span>
                                                                                                        <tr/>
                                                                                                        </div>
                                                                                                            <div className="r"><a name="1480482"></a> <img src="/icons/normal_post.gif" alt=''/> <b><a href="/1480482/nairalands-new-dynamic-ads-beta">Nairaland&#x27;s New Dynamic Ads - Beta Test</a> </b>                                                                                                                <a href="https://www.nairaland.com/1480482/nairalands-new-dynamic-ads-beta/1">(2)</a> <a href="https://www.nairaland.com/1480482/nairalands-new-dynamic-ads-beta/2">(3)</a>                                                                                                                <a href="https://www.nairaland.com/1480482/nairalands-new-dynamic-ads-beta/3">(4)</a> ... <a href="https://www.nairaland.com/1480482/nairalands-new-dynamic-ads-beta/7">(8)</a>                                                                                                                <a href="https://www.nairaland.com/1480482/nairalands-new-dynamic-ads-beta/8">(9)</a> <a href="https://www.nairaland.com/1480482/nairalands-new-dynamic-ads-beta/9">(10)</a>                                                                                                                <b>*</b> <br/><span class="s">by <b><a href="/seun">Seun</a></b>. <b>311</b> posts &amp; <b>83395</b> views. <b>11:13am</b> On <b>Nov 14</b>, <b>2013</b>  (<b><a href="/seun">Seun</a></b>)</span>
                                                                                                             </div>

                                                                                                             <p>
                        <b>(1)</b> (of <b>1</b> pages) (<a href="https://www.nairaland.com/newtopic?board=80">Create New Topic</a>) (<a class="unft" onClick="handlefollows('https://www.nairaland.com/do_unfollowboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fads&amp;board=80', 'https://www.nairaland.com/do_followboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fads&amp;board=80', '0', 'Follow', 'Un-Follow', 'unft'); return false;"
                                href="https://www.nairaland.com/do_followboard?session=3C654A71F75BEE5DAD68EA20F687886DE56B390E2479BB3C934DE162CE180095&amp;redirect=%2Fads&amp;board=80">Follow</a>) (<a href="https://www.nairaland.com/mailmods?board=80">Mail Mods</a>)
                            <p> (Moderators: <a href="https://www.nairaland.com/seun">Seun</a>, <a href="https://www.nairaland.com/mynd44">Mynd44</a>)
                                <div class="vertipics"><a href="/hopto/ads/111" rel="sponsored"><img src="https://www.nairaland.com/vertipics/ujsti16vmkvlxuxyzafqz3hlbs1j0np6.png" alt=''/></a><a href="/hopto/ads/111" rel="sponsored"><img src="https://www.nairaland.com/vertipics/ujsti16vmkvlxuxyzafqz3hlbs1j0np6.png" alt=''/></a>
                                    <a
                                        href="/hopto/ads/14697" rel="sponsored"><img src="https://www.nairaland.com/vertipics/kxwks5gc1klg169nnw41c8q6zpuawuur.jpg" alt=''/></a>
                                </div>
                                </p>
                                <p class="nocopy">Viewing this board
                                <a href="/racheal12">Racheal12</a> and 1 guest(s)</p>
                                
                                    <p class="small">(<a href="#up"><b>Go Up</b></a>)
                                        <p/>
                                        </p>
                                        </p>


                                        
                                                <tr/>
                                                    <div class="lw">
                                                        <p>
                                                            <form action="/search"> <input type="text" name="q" size="32"/>
                                                                <input type="submit" name="search" value="Search"/></form>Sections: <a href="/politics">politics</a> <a href="/politics/1">(1)</a> <a href="/business">business</a> <a href="/autos">autos</a>                                                            <a href="/autos/1">(1)</a> <a href="/jobs">jobs</a> <a href="/jobs/1">(1)</a> <a href="/career">career</a> <a href="/education">education</a> <a href="/education/1">(1)</a> <a href="/romance">romance</a>                                                            <a href="/computers">computers</a> <a href="/phones">phones</a> <a href="/travel">travel</a> <a href="/sports">sports</a> <a href="/fashion">fashion</a> <a href="/health">health</a> <br/> <a href="/religion">religion</a>                                                            <a href="/celebs">celebs</a> <a href="/tv-movies">tv-movies</a> <a href="/music-radio">music-radio</a> <a href="/literature">literature</a> <a href="/webmasters">webmasters</a> <a href="/programming">programming</a>                                                            <a href="/techmarket">techmarket</a>
                                                            <p>Links: <a href="/news" title="Page 1, Nairaland News ">(1)</a> <a href="/news/1" title="Page 2, Nairaland News ">(2)</a> <a href="/news/2" title="Page 3, Nairaland News ">(3)</a> <a href="/news/3"
                                                                    title="Page 4, Nairaland News ">(4)</a> <a href="/news/4" title="Page 5, Nairaland News ">(5)</a> <a href="/news/5" title="Page 6, Nairaland News ">(6)</a> <a href="/news/6" title="Page 7, Nairaland News ">(7)</a>                                                                <a href="/news/7" title="Page 8, Nairaland News ">(8)</a> <a href="/news/8" title="Page 9, Nairaland News ">(9)</a> <a href="/news/9" title="Page 10, Nairaland News ">(10)</a>
                                                                <p><b><a href="/" title="Nigerian Forum">Nairaland</a></b> - Copyright &copy; 2005 - 2022 <a href="http://www.seunosewa.com" title="Seun">Oluwaseun Osewa</a>. All rights reserved. See <a href="https://www.nairaland.com/1049481/how-place-targeted-ads-nairaland">How To Advertise</a>.
                                                                    113<br/><b>Disclaimer</b>: Every Nairaland member is <b>solely responsible</b> for <b>anything</b> that he/she <b>posts</b> or <b>uploads</b> on Nairaland.
                                                         </p>
                                                         </p>
                                                         </p>
                                                         </div>


                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                        
    </div>
  )
}

export default NairalandAds